apiVersion: v1
kind: Service
metadata:
  name: fermentation
spec:
  selector:
    app: fermentation
  ports:
    - name: fermentation
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      nodePort: {{.Values.service.port}}
      protocol: TCP
  type: NodePort