# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mongo
  imagePullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


service:
  type: NodePort
  port: 27017

pv:
  spec:
    hostPath:
      path: /run/desktop/mnt/host/c/DockerVolumes/mongo  #docker desktop
      # path: /mnt/c/DockerVolumes/mongo                     #wsl ubuntu

