apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  selector:
    app: mqtt
  ports:
    - name: tcp
      port: 1883
      targetPort: 1883
      nodePort: 1883
      protocol: TCP
    - name: websocket
      port: 9001
      targetPort: 9001
      nodePort: 9001
      protocol: TCP
  type: NodePort