apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - name: user
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      nodePort: {{.Values.service.port}}
      protocol: TCP
  type: NodePort