apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: mongodb
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: {{.Values.pv.spec.hostPath.path}}
    # path: /mnt/host/c/DockerVolumes/mongo
    type: DirectoryOrCreate
