apiVersion: v1
kind: Service
metadata:
  name: entry
spec:
  selector:
    app: entry
  ports:
    - name: entry
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      nodePort: {{.Values.service.port}}
      protocol: TCP
  type: NodePort