apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: tcp
      port: 15672
      targetPort: 15672
      nodePort: 15672
      protocol: TCP
    - name: tcp2
      port: 5672
      targetPort: 5672
      nodePort: 5672
      protocol: TCP
  type: NodePort