apiVersion: v1
kind: Service
metadata:
  name: ems
spec:
  selector:
    app: ems
  ports:
    - name: ems
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      nodePort: {{.Values.service.port}}
      protocol: TCP
  type: NodePort