apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: {{.Values.image.repository}}
        command:
          - etcd
        args:
          - --name=etcd
          - --advertise-client-urls=http://localhost:2379
          - --listen-client-urls=http://0.0.0.0:2379
          - --listen-peer-urls=http://0.0.0.0:2380
          - --initial-advertise-peer-urls=http://etcd:2380
          - --initial-cluster-token=etcd-cluster-1
          - --initial-cluster-state=new
          - --initial-cluster=etcd=http://etcd:2380
          - --data-dir=/etcd-data
        ports:
        - containerPort: {{.Values.service.port}}
        - containerPort: 2380
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
      volumes:
      - name: etcd-data
        hostPath:
          path: /path/to/local/folder