apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  selector:
    app: etcd
  ports:
    - name: etcd
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      nodePort: {{.Values.service.port}}
      protocol: TCP
  type: NodePort